apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
      name: http
  selector:
    app: petclinic
  type: NodePort
    