apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  selector:
    app: petclinic
    version: v1.0.1
  ports:
  - port: 8080
    name: http
    targetPort: 8080
    nodePort: 31080
  type: NodePort
